// This file provides types for the API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package isslocation

// ISSLocation defines a model
type ISSLocation struct {
	Timestamp   int         `json:"timestamp,omitzero"`
	IssPosition ISSPosition `json:"iss_position"`
	Message     string      `json:"message,omitzero"`
}

// ISSPosition defines a model
type ISSPosition struct {
	Longitude string `json:"longitude,omitzero"`
	Latitude  string `json:"latitude,omitzero"`
}

// PeopleInSpace defines a model
type PeopleInSpace struct {
	People  Astronauts `json:"people,omitempty"`
	Number  int        `json:"number,omitzero"`
	Message string     `json:"message,omitzero"`
}

// Astronauts defines a model
type Astronauts []Astronaut

// Astronaut defines a model
type Astronaut struct {
	Craft string `json:"craft,omitzero"`
	Name  string `json:"name,omitzero"`
}
