// This file provides types for the API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package isslocation

// GetIssNowJSONOkJSONResponse defines a model
type GetIssNowJSONOkJSONResponse struct {
	Timestamp   int                                    `json:"timestamp,omitzero"`
	IssPosition GetIssNowJSONOkJSONResponseIssPosition `json:"iss_position"`
	Message     string                                 `json:"message,omitzero"`
}

// GetIssNowJSONOkJSONResponseIssPosition defines a model
type GetIssNowJSONOkJSONResponseIssPosition struct {
	Longitude string `json:"longitude,omitzero"`
	Latitude  string `json:"latitude,omitzero"`
}
